// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package tcpproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TcpServerServiceClient is the client API for TcpServerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TcpServerServiceClient interface {
	Send(ctx context.Context, in *TcpProtoPack, opts ...grpc.CallOption) (*TcpProtoPack, error)
}

type tcpServerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTcpServerServiceClient(cc grpc.ClientConnInterface) TcpServerServiceClient {
	return &tcpServerServiceClient{cc}
}

func (c *tcpServerServiceClient) Send(ctx context.Context, in *TcpProtoPack, opts ...grpc.CallOption) (*TcpProtoPack, error) {
	out := new(TcpProtoPack)
	err := c.cc.Invoke(ctx, "/tcpProto.tcpServerService/Send", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TcpServerServiceServer is the server API for TcpServerService service.
// All implementations should embed UnimplementedTcpServerServiceServer
// for forward compatibility
type TcpServerServiceServer interface {
	Send(context.Context, *TcpProtoPack) (*TcpProtoPack, error)
}

// UnimplementedTcpServerServiceServer should be embedded to have forward compatible implementations.
type UnimplementedTcpServerServiceServer struct {
}

func (UnimplementedTcpServerServiceServer) Send(context.Context, *TcpProtoPack) (*TcpProtoPack, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Send not implemented")
}

// UnsafeTcpServerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TcpServerServiceServer will
// result in compilation errors.
type UnsafeTcpServerServiceServer interface {
	mustEmbedUnimplementedTcpServerServiceServer()
}

func RegisterTcpServerServiceServer(s grpc.ServiceRegistrar, srv TcpServerServiceServer) {
	s.RegisterService(&TcpServerService_ServiceDesc, srv)
}

func _TcpServerService_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TcpProtoPack)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TcpServerServiceServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tcpProto.tcpServerService/Send",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TcpServerServiceServer).Send(ctx, req.(*TcpProtoPack))
	}
	return interceptor(ctx, in, info, handler)
}

// TcpServerService_ServiceDesc is the grpc.ServiceDesc for TcpServerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TcpServerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tcpProto.tcpServerService",
	HandlerType: (*TcpServerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Send",
			Handler:    _TcpServerService_Send_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/tcpproto/tcp_server.proto",
}
