// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: proto/common/error.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrCode int32

const (
	ErrCode_Nil       ErrCode = 0     // nil
	ErrCode_NoJwt     ErrCode = 40011 // 没有携带校验信息
	ErrCode_NoAuth    ErrCode = 40012 // 校验信息异常
	ErrCode_JwtExpire ErrCode = 40013 // 校验信息过期
)

// Enum value maps for ErrCode.
var (
	ErrCode_name = map[int32]string{
		0:     "Nil",
		40011: "NoJwt",
		40012: "NoAuth",
		40013: "JwtExpire",
	}
	ErrCode_value = map[string]int32{
		"Nil":       0,
		"NoJwt":     40011,
		"NoAuth":    40012,
		"JwtExpire": 40013,
	}
)

func (x ErrCode) Enum() *ErrCode {
	p := new(ErrCode)
	*p = x
	return p
}

func (x ErrCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrCode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_common_error_proto_enumTypes[0].Descriptor()
}

func (ErrCode) Type() protoreflect.EnumType {
	return &file_proto_common_error_proto_enumTypes[0]
}

func (x ErrCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrCode.Descriptor instead.
func (ErrCode) EnumDescriptor() ([]byte, []int) {
	return file_proto_common_error_proto_rawDescGZIP(), []int{0}
}

var File_proto_common_error_proto protoreflect.FileDescriptor

var file_proto_common_error_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2a, 0x3e, 0x0a, 0x07, 0x45, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x07, 0x0a,
	0x03, 0x4e, 0x69, 0x6c, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x05, 0x4e, 0x6f, 0x4a, 0x77, 0x74, 0x10,
	0xcb, 0xb8, 0x02, 0x12, 0x0c, 0x0a, 0x06, 0x4e, 0x6f, 0x41, 0x75, 0x74, 0x68, 0x10, 0xcc, 0xb8,
	0x02, 0x12, 0x0f, 0x0a, 0x09, 0x4a, 0x77, 0x74, 0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x10, 0xcd,
	0xb8, 0x02, 0x42, 0x23, 0x5a, 0x21, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x43, 0x65, 0x6e,
	0x74, 0x65, 0x72, 0x2d, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_common_error_proto_rawDescOnce sync.Once
	file_proto_common_error_proto_rawDescData = file_proto_common_error_proto_rawDesc
)

func file_proto_common_error_proto_rawDescGZIP() []byte {
	file_proto_common_error_proto_rawDescOnce.Do(func() {
		file_proto_common_error_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_common_error_proto_rawDescData)
	})
	return file_proto_common_error_proto_rawDescData
}

var file_proto_common_error_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_common_error_proto_goTypes = []interface{}{
	(ErrCode)(0), // 0: common.ErrCode
}
var file_proto_common_error_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_common_error_proto_init() }
func file_proto_common_error_proto_init() {
	if File_proto_common_error_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_common_error_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_common_error_proto_goTypes,
		DependencyIndexes: file_proto_common_error_proto_depIdxs,
		EnumInfos:         file_proto_common_error_proto_enumTypes,
	}.Build()
	File_proto_common_error_proto = out.File
	file_proto_common_error_proto_rawDesc = nil
	file_proto_common_error_proto_goTypes = nil
	file_proto_common_error_proto_depIdxs = nil
}
