// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.2
// source: proto/controlProto/server.proto

package controlProto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServerCommand int32

const (
	ServerCommand_CMD_ID_HELLO              ServerCommand = 0
	ServerCommand_CMD_ID_HEARTBEAT          ServerCommand = 1
	ServerCommand_CMD_ID_AUTH               ServerCommand = 2
	ServerCommand_CMD_ID_UPDATE_SERVER_INFO ServerCommand = 3
	ServerCommand_CMD_ID_CLIENT_ACTION      ServerCommand = 4
)

// Enum value maps for ServerCommand.
var (
	ServerCommand_name = map[int32]string{
		0: "CMD_ID_HELLO",
		1: "CMD_ID_HEARTBEAT",
		2: "CMD_ID_AUTH",
		3: "CMD_ID_UPDATE_SERVER_INFO",
		4: "CMD_ID_CLIENT_ACTION",
	}
	ServerCommand_value = map[string]int32{
		"CMD_ID_HELLO":              0,
		"CMD_ID_HEARTBEAT":          1,
		"CMD_ID_AUTH":               2,
		"CMD_ID_UPDATE_SERVER_INFO": 3,
		"CMD_ID_CLIENT_ACTION":      4,
	}
)

func (x ServerCommand) Enum() *ServerCommand {
	p := new(ServerCommand)
	*p = x
	return p
}

func (x ServerCommand) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServerCommand) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_controlProto_server_proto_enumTypes[0].Descriptor()
}

func (ServerCommand) Type() protoreflect.EnumType {
	return &file_proto_controlProto_server_proto_enumTypes[0]
}

func (x ServerCommand) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServerCommand.Descriptor instead.
func (ServerCommand) EnumDescriptor() ([]byte, []int) {
	return file_proto_controlProto_server_proto_rawDescGZIP(), []int{0}
}

type CommandItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerId    string        `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	ServerToken []byte        `protobuf:"bytes,2,opt,name=server_token,json=serverToken,proto3" json:"server_token,omitempty"`
	Command     ServerCommand `protobuf:"varint,3,opt,name=command,proto3,enum=controlProto.ServerCommand" json:"command,omitempty"`
	CommandBuf  []byte        `protobuf:"bytes,4,opt,name=command_buf,json=commandBuf,proto3" json:"command_buf,omitempty"`
	SeqID       string        `protobuf:"bytes,5,opt,name=SeqID,proto3" json:"SeqID,omitempty"`
}

func (x *CommandItem) Reset() {
	*x = CommandItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_controlProto_server_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommandItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandItem) ProtoMessage() {}

func (x *CommandItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controlProto_server_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandItem.ProtoReflect.Descriptor instead.
func (*CommandItem) Descriptor() ([]byte, []int) {
	return file_proto_controlProto_server_proto_rawDescGZIP(), []int{0}
}

func (x *CommandItem) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *CommandItem) GetServerToken() []byte {
	if x != nil {
		return x.ServerToken
	}
	return nil
}

func (x *CommandItem) GetCommand() ServerCommand {
	if x != nil {
		return x.Command
	}
	return ServerCommand_CMD_ID_HELLO
}

func (x *CommandItem) GetCommandBuf() []byte {
	if x != nil {
		return x.CommandBuf
	}
	return nil
}

func (x *CommandItem) GetSeqID() string {
	if x != nil {
		return x.SeqID
	}
	return ""
}

var File_proto_controlProto_server_proto protoreflect.FileDescriptor

var file_proto_controlProto_server_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xbb, 0x01, 0x0a, 0x0b, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x12,
	0x1b, 0x0a, 0x09, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12,
	0x35, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x1b, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x07, 0x63,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x5f, 0x62, 0x75, 0x66, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x63, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x42, 0x75, 0x66, 0x12, 0x14, 0x0a, 0x05, 0x53, 0x65, 0x71, 0x49, 0x44,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x53, 0x65, 0x71, 0x49, 0x44, 0x2a, 0x81, 0x01,
	0x0a, 0x0d, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12,
	0x10, 0x0a, 0x0c, 0x43, 0x4d, 0x44, 0x5f, 0x49, 0x44, 0x5f, 0x48, 0x45, 0x4c, 0x4c, 0x4f, 0x10,
	0x00, 0x12, 0x14, 0x0a, 0x10, 0x43, 0x4d, 0x44, 0x5f, 0x49, 0x44, 0x5f, 0x48, 0x45, 0x41, 0x52,
	0x54, 0x42, 0x45, 0x41, 0x54, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x43, 0x4d, 0x44, 0x5f, 0x49,
	0x44, 0x5f, 0x41, 0x55, 0x54, 0x48, 0x10, 0x02, 0x12, 0x1d, 0x0a, 0x19, 0x43, 0x4d, 0x44, 0x5f,
	0x49, 0x44, 0x5f, 0x55, 0x50, 0x44, 0x41, 0x54, 0x45, 0x5f, 0x53, 0x45, 0x52, 0x56, 0x45, 0x52,
	0x5f, 0x49, 0x4e, 0x46, 0x4f, 0x10, 0x03, 0x12, 0x18, 0x0a, 0x14, 0x43, 0x4d, 0x44, 0x5f, 0x49,
	0x44, 0x5f, 0x43, 0x4c, 0x49, 0x45, 0x4e, 0x54, 0x5f, 0x41, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x10,
	0x04, 0x32, 0x50, 0x0a, 0x0c, 0x50, 0x75, 0x73, 0x68, 0x54, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x12, 0x40, 0x0a, 0x08, 0x50, 0x75, 0x73, 0x68, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x19, 0x2e,
	0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x1a, 0x19, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72,
	0x6f, 0x6c, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x49,
	0x74, 0x65, 0x6d, 0x42, 0x29, 0x5a, 0x27, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x43, 0x65,
	0x6e, 0x74, 0x65, 0x72, 0x2d, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_controlProto_server_proto_rawDescOnce sync.Once
	file_proto_controlProto_server_proto_rawDescData = file_proto_controlProto_server_proto_rawDesc
)

func file_proto_controlProto_server_proto_rawDescGZIP() []byte {
	file_proto_controlProto_server_proto_rawDescOnce.Do(func() {
		file_proto_controlProto_server_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_controlProto_server_proto_rawDescData)
	})
	return file_proto_controlProto_server_proto_rawDescData
}

var file_proto_controlProto_server_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_controlProto_server_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_controlProto_server_proto_goTypes = []interface{}{
	(ServerCommand)(0),  // 0: controlProto.ServerCommand
	(*CommandItem)(nil), // 1: controlProto.CommandItem
}
var file_proto_controlProto_server_proto_depIdxs = []int32{
	0, // 0: controlProto.CommandItem.command:type_name -> controlProto.ServerCommand
	1, // 1: controlProto.PushToServer.PushTask:input_type -> controlProto.CommandItem
	1, // 2: controlProto.PushToServer.PushTask:output_type -> controlProto.CommandItem
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_controlProto_server_proto_init() }
func file_proto_controlProto_server_proto_init() {
	if File_proto_controlProto_server_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_controlProto_server_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommandItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_controlProto_server_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_controlProto_server_proto_goTypes,
		DependencyIndexes: file_proto_controlProto_server_proto_depIdxs,
		EnumInfos:         file_proto_controlProto_server_proto_enumTypes,
		MessageInfos:      file_proto_controlProto_server_proto_msgTypes,
	}.Build()
	File_proto_controlProto_server_proto = out.File
	file_proto_controlProto_server_proto_rawDesc = nil
	file_proto_controlProto_server_proto_goTypes = nil
	file_proto_controlProto_server_proto_depIdxs = nil
}
